package com.tryden.simplenfl.network.response.models.player

data class PlayerResponse(
    val `$ref`: String = "",
    val active: Boolean = false,
    val age: Int = 0,
    val alternateIds: com.tryden.simplenfl.network.response.models.player.AlternateIds = com.tryden.simplenfl.network.response.models.player.AlternateIds(),
    val birthPlace: com.tryden.simplenfl.network.response.models.player.BirthPlace = com.tryden.simplenfl.network.response.models.player.BirthPlace(),
    val college: com.tryden.simplenfl.network.response.models.player.College = com.tryden.simplenfl.network.response.models.player.College(),
    val collegeAthlete: com.tryden.simplenfl.network.response.models.player.CollegeAthlete = com.tryden.simplenfl.network.response.models.player.CollegeAthlete(),
    val contracts: com.tryden.simplenfl.network.response.models.player.Contracts = com.tryden.simplenfl.network.response.models.player.Contracts(),
    val dateOfBirth: String = "",
    val debutYear: Int = 0,
    val displayHeight: String = "",
    val displayName: String = "",
    val displayWeight: String = "",
    val draft: com.tryden.simplenfl.network.response.models.player.Draft = com.tryden.simplenfl.network.response.models.player.Draft(),
    val experience: com.tryden.simplenfl.network.response.models.player.Experience = com.tryden.simplenfl.network.response.models.player.Experience(),
    val firstName: String = "",
    val fullName: String = "",
    val guid: String = "",
    val headshot: com.tryden.simplenfl.network.response.models.player.Headshot = com.tryden.simplenfl.network.response.models.player.Headshot(),
    val height: Int = 0,
    val id: String = "",
    val jersey: String = "",
    val lastName: String = "",
    val linked: Boolean = false,
    val links: List<com.tryden.simplenfl.network.response.models.player.Link> = listOf(),
    val position: com.tryden.simplenfl.network.response.models.player.Position = com.tryden.simplenfl.network.response.models.player.Position(),
    val shortName: String = "",
    val slug: String = "",
    val statistics: com.tryden.simplenfl.network.response.models.player.Statistics = com.tryden.simplenfl.network.response.models.player.Statistics(),
    val statisticslog: com.tryden.simplenfl.network.response.models.player.Statisticslog = com.tryden.simplenfl.network.response.models.player.Statisticslog(),
    val status: com.tryden.simplenfl.network.response.models.player.Status = com.tryden.simplenfl.network.response.models.player.Status(),
    val team: com.tryden.simplenfl.network.response.models.player.TeamDraft = com.tryden.simplenfl.network.response.models.player.TeamDraft(),
    val type: String = "",
    val uid: String = "",
    val weight: Int = 0
)